DROP DATABASE IF EXISTS Gunathilake_23610903;
CREATE DATABASE Gunathilake_23610903;
USE Gunathilake_23610903;

CREATE TABLE Country(
    countryID INT AUTO_INCREMENT PRIMARY KEY,
    countryName VARCHAR(100) NOT NULL UNIQUE,
    countryCode CHAR(3) NOT NULL UNIQUE
);

CREATE TABLE Genre(
    genreID INT AUTO_INCREMENT PRIMARY KEY,
    genreName VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Award(
    awardID INT AUTO_INCREMENT PRIMARY KEY,
    awardName VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Person(
    personID INT PRIMARY KEY AUTO_INCREMENT,
    fullName VARCHAR(100) NOT NULL,
    birthDate DATE,
    countryID INT,
    FOREIGN KEY (countryID) REFERENCES Country(countryID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE Festival(
    festivalID INT AUTO_INCREMENT PRIMARY KEY,
    festivalName VARCHAR(100) NOT NULL UNIQUE,
    countryID INT NOT NULL,
    FOREIGN KEY (countryID) REFERENCES Country(countryID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE Film(
    filmID INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    releaseYear INT,
    duration INT,
    countryID INT,
    rating DECIMAL(3,1) CHECK (rating >= 0 AND rating <= 10),
    FOREIGN KEY (countryID) REFERENCES Country(countryID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE FestivalEdition(
    editionID INT AUTO_INCREMENT PRIMARY KEY,
    festivalID INT NOT NULL,
    year INT NOT NULL,
    ceremonyNumber INT, -- TYPO FIXED HERE
    startDate DATE NOT NULL,
    endDate DATE NOT NULL,
    FOREIGN KEY (festivalID) REFERENCES Festival(festivalID) ON DELETE CASCADE ON UPDATE CASCADE,
    CHECK (endDate >= startDate)
);

CREATE TABLE FilmGenre(
    filmID INT,
    genreID INT,
    PRIMARY KEY (filmID, genreID),
    FOREIGN KEY (filmID) REFERENCES Film(filmID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (genreID) REFERENCES Genre(genreID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Nomination(
    nominationID INT AUTO_INCREMENT PRIMARY KEY,
    editionID INT NOT NULL,
    filmID INT NOT NULL,
    awardID INT NOT NULL,
    personID INT,
    isWinner BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (editionID) REFERENCES FestivalEdition(editionID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (awardID) REFERENCES Award(awardID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (filmID) REFERENCES Film(filmID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (personID) REFERENCES Person(personID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE FilmDirector(
    filmID INT,
    personID INT,
    PRIMARY KEY (filmID, personID),
    FOREIGN KEY (filmID) REFERENCES Film(filmID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (personID) REFERENCES Person(personID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE FilmActor(
    filmID INT,
    personID INT,
    PRIMARY KEY (filmID, personID),
    FOREIGN KEY (filmID) REFERENCES Film(filmID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (personID) REFERENCES Person(personID) ON DELETE CASCADE ON UPDATE CASCADE
);